### ISSUE TITLE
Error PHP : uncaught error Call to a member function getID()

### ISSUE THREAD

**Issue by amma35** [pluginsGLPI/satisfaction#4]
``` Uncaught Error: Call to a member function getID() on boolean in /usr/share/glpi/plugins/satisfaction/inc/surveyanswer.class.php:283\nStack trace:\n#0 /usr/share/glpi/inc/plugin.class.php(1125): PluginSatisfactionSurveyAnswer::addNotificationDatas(Object(NotificationTargetTicket))\n#1 /usr/share/glpi/inc/notificationtarget.class.php(1073): Plugin::doHook('item_get_datas', Object(NotificationTargetTicket))\n#2 /usr/share/glpi/inc/notificationtemplate.class.php(245): NotificationTarget->getForTemplate('satisfaction', Array)\n#3 /usr/share/glpi/inc/notificationevent.class.php(170): NotificationTemplate->getTemplateByLanguage(Object(NotificationTargetTicket), Array, 'satisfaction', Array)\n#4 /usr/share/glpi/inc/ticketsatisfaction.class.php(184): NotificationEvent::raiseEvent('satisfaction', Object(Ticket))\n#5 /usr/share/glpi/inc/commondbtm.class.php(853): TicketSatisfaction->post_addItem()\n#6 /usr/share/glpi/inc/ticket.class.php(1388): CommonDBTM->add(Array)\n#7 /usr/share/glpi/inc/commondbtm.class.php(1174): Ticket->po in /usr/share/glpi/plugins/satisfaction/inc/surveyanswer.class.php on line 283, referer: /front/ticket.form.php?id=47195```

**Comment by amma35** [comment]
Fix in https://github.com/pluginsGLPI/satisfaction/commit/3d6462360dbf937f633be04917ae77bddeeae26c
